LyricsUniverse/Controllers/AdminController.cs
using LyricsUniverse.Models;
using LyricsUniverse.Models.Entities;
using LyricsUniverse.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LyricsUniverse.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly LyricsDbContext _context;

        public AdminController(LyricsDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var songs = _context.Songs
                .Include(s => s.Artist)
                .OrderBy(s => s.Title)
                .ToList();

            var model = new SongsViewModel
            {
                Songs = songs,
                SelectedSong = null
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int songId)
        {
            var song = _context.Songs.FirstOrDefault(s => s.SongId == songId);

            var model = new EditViewModel
            {
                Title = song.Title,
                Text = song.Text,
                Id = songId
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditViewModel model, int songId)
        {
            _context.Songs.Where(s => s.SongId == songId)
            .ExecuteUpdate(b =>
                b.SetProperty(s => s.Title, model.Title)
            );

            _context.Songs.Where(s => s.SongId == songId)
            .ExecuteUpdate(b =>
                b.SetProperty(s => s.Text, model.Text)
            );

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int songId)
        {
            var song = _context.Songs.FirstOrDefault(s => s.SongId == songId);
            _context.Songs.Remove(song);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(AddViewModel model)
        {
            if (ModelState.IsValid)
            {
                Song newSong = new Song();

                var artist = _context.Artists.FirstOrDefault(e => e.Title.ToUpper() == model.Artist.ToUpper());
                if (artist != null)
                {
                    var song = _context.Songs.FirstOrDefault(e => e.Title.ToUpper() == model.Title.ToUpper());

                    if (song != null)
                    {
                        ModelState.AddModelError(string.Empty, "Такая песня уже есть в базе данных. " +
                            "Вы можете отредактировать ее в любой момент.");
                        return View(model);
                    }

                    newSong.Artist = artist;
                }
                else
                {
                    Artist newArtist = new Artist
                    {
                        Title = model.Artist,
                    };
                    _context.Artists.Add(newArtist);
                    _context.SaveChanges();

                    newSong.Artist = newArtist;
                }

                newSong.Title = model.Title;
                newSong.Text = model.Text;

                _context.Songs.Add(newSong);
                _context.SaveChanges();
            }
            return RedirectToAction("Add");
        }
    }
}

LyricsUniverse/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using LyricsUniverse.Models;
using LyricsUniverse.Models.Entities;
using Microsoft.AspNetCore.Identity;
using LyricsUniverse.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace LyricsUniverse.Controllers
{
    [Authorize(Roles = "authorizedUser")]
    public class FavoritesController : Controller
    {
        private readonly LyricsDbContext _context;
        private readonly UserManager<User> _userManager;

        public FavoritesController (LyricsDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index(int songId = -1)
        {
            var model = new FavoriteSongsViewModel();
            var userId = _userManager.GetUserId(User);

            model.SelectedSong = _context.Songs.Find(songId);
            model.FavoriteSongs = _context.FavoriteSongs
                .Include(fs => fs.Song)
                .ThenInclude(s => s.Artist)
                .Where(fs => fs.UserId == userId)
                .OrderBy(fs => fs.Song.Title)
                .ToList();

            return View(model);
        }

        public IActionResult Add(int songId)
        {
            var userId = _userManager.GetUserId(User);

            if (userId != null)
            {
                var favoriteSong = _context.FavoriteSongs.FirstOrDefault(fs => fs.UserId == userId &&
                    fs.SongId == songId);

                if (favoriteSong is null)
                {
                    _context.FavoriteSongs.Add(new FavoriteSong
                    {
                        UserId = userId,
                        SongId = songId
                    });
                    _context.SaveChanges();
                   
                }
            }
            return Redirect($"/Favorites?songId={songId}");
        }

        public IActionResult Delete(int songId)
        {
            var userId = _userManager.GetUserId(User);

            if (userId != null)
            {
                var favoriteSong = _context.FavoriteSongs.FirstOrDefault(fs => fs.UserId == userId &&
                    fs.SongId == songId);

                if (favoriteSong is not null)
                {
                    _context.FavoriteSongs.Remove(favoriteSong);
                    _context.SaveChanges();
                }
            }
            return Redirect($"/Song/Id/{songId}");
        }
    }
}

LyricsUniverse/Controllers/SongController.cs
using LyricsUniverse.Models;
using LyricsUniverse.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LyricsUniverse.Controllers
{
    public class SongController : Controller
    {
        private readonly LyricsDbContext _context;

        public SongController(LyricsDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Id(int id)
        {
            var selectedSong = _context.Songs.Find(id);
            return View(new SongsViewModel
            {
                Songs = _context.Songs.Include(s => s.Artist).ToList(),
                SelectedSong = selectedSong
            });
        }
    }
}

LyricsUniverse/Views/Shared/AdminLayoutPartial.cshtml
<ul class="list-group" id="menu">
    <li class="list-group-item">
        <a class="text-dark link" asp-controller="Admin" asp-action="Index">Список песен</a>
    </li>
    <li class="list-group-item">
        <a class="text-dark link" asp-controller="Admin" asp-action="Add">Добавить</a>
    </li>
    <li class="list-group-item">
        <a class="text-dark link" asp-controller="Home" asp-action="Index">На сайт</a>
    </li>
</ul>

LyricsUniverse/Views/Shared/FavoriteListPartial.cshtml
<ul class="list-group">
    @if (Model.FavoriteSongs.Count > 0)
    {
        @foreach (var fList in Model.FavoriteSongs)
        {
            <li class="list-group-item">
                <a href="@Url.Action("Index", "Favorites", new { songId = fList.Song.SongId })" class="text-dark link">@fList.Song.Title - @fList.Song.Artist.Title</a>
            </li>
        }
    }
    else
    {
        <li>
            <p class="text-dark">Список пуст</p>
        </li>
    }
</ul>

LyricsUniverse/Views/Shared/SongsPartial.cshtml
<ul class="list-group">
    @if (Model.SelectedSong != null)
    {
        @foreach (var song in Model.SelectedSong.Artist.Songs)
        {
            <li class="list-group-item">
                <a href="@Url.Action("Id", "Song", new { id = song.SongId })" class="text-dark link">@song.Title</a>
            </li>
        }
    }
    else
    {
        <li class="list-group-item">
            <p class="text-dark">Список пуст</p>
        </li>
    }
</ul>

LyricsUniverse/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE HTML>
<html lang="ru">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Admin Universe</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="d-none d-md-block">
                    <div class="mt-3">
                        <div class="mb-2">
                            <p class="lead text-center">Панель администратора</p>
                        </div>
                            @await Html.PartialAsync("AdminLayoutPartial")
                        </div>
                </div>
                <div class="d-md-none">
                    <div class="mt-3 mb-1 d-flex">
                        <button class="btn btn-primary btn-white btn-block fs-6" type="button" data-bs-toggle="collapse" data-bs-target="#adminList" aria-expanded="false" aria-controls="adminList" aria-label="Toggle navigation">
                            Панель Администратора
                        </button>
                    </div>
                    <div class="collapse mt-3" id="adminList">
                        @await Html.PartialAsync("AdminLayoutPartial")
                    </div>
                </div>
            </div>

            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

LyricsUniverse/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="ru">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Lyrics Universe</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/styles.css">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lyrics Universe</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            <a class="nav-link" asp-area="" asp-controller="Favorites" asp-action="Index">Избранное</a>
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Аккаунт</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <div>
            <main>
                @RenderBody()
            </main>
         </div>

        <footer>

        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>